#!/bin/bash
#SBATCH --job-name=outcome_dist
#SBATCH --qos=nf
#SBATCH --time=02:00:00
#SBATCH --mem=8G
#SBATCH --output=logs/outcome_distribution_%j.out

# ============================================================================
# Dataset-wide outcome distribution
# ============================================================================
#
# Tallies the eight outcome states over every per-cohort recruitment file.
# Output feeds the Validation table in recruitment/README.md and section 7 of
# the Paper 1 methodology document.
#
# The SBATCH directives above are specific to ECMWF's Atos HPCF.
#
# Submit from recruitment/scripts:
#   sbatch outcome_distribution.sh
# ============================================================================

set -euo pipefail

module load python3

export PYTHONUNBUFFERED=1

SCRIPT_DIR="${SLURM_SUBMIT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
RECRUITMENT_DIR="$(dirname "$SCRIPT_DIR")"

mkdir -p "${SCRIPT_DIR}/logs"

# Outputs are written into data/, which is gitignored: this repository holds
# the code, while results are either regenerated by the user or downloaded
# from Zenodo. The CSV names do not match the YYYY_MM_DD.nc pattern that
# archive_by_year.sh selects on, so they are not swept into the archives.
python3 "${SCRIPT_DIR}/outcome_distribution.py" \
    --data       "${RECRUITMENT_DIR}/data" \
    --out        "${RECRUITMENT_DIR}/data/outcome_distribution.csv" \
    --per-cohort "${RECRUITMENT_DIR}/data/outcome_per_cohort.csv"
